-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE public."systemPersonnel"
(
    id integer NOT NULL,
    name character varying(20) NOT NULL,
    surname character varying(20) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public."jobTitle"
(
    "positionName" character varying(30) NOT NULL,
    "positionId" integer NOT NULL,
    PRIMARY KEY ("positionName")
);

CREATE TABLE public.employee
(
    "employeeId" integer NOT NULL,
    name character varying(15) NOT NULL,
    surname character varying(20) NOT NULL,
    "nationalId" character varying(11) NOT NULL,
    "birthYear" bit varying(4) NOT NULL,
    "eMail" "char" NOT NULL,
    password "char" NOT NULL,
    PRIMARY KEY ("employeeId")
);

CREATE TABLE public.employer
(
    "employerId" integer NOT NULL,
    "companyName" "char" NOT NULL,
    website "char" NOT NULL,
    "corporateMail" "char" NOT NULL,
    "phoneNumber" character varying(11) NOT NULL,
    password "char" NOT NULL,
    PRIMARY KEY ("employerId")
);

CREATE TABLE public."systemPersonnelValidator"
(
    id integer NOT NULL,
    "eMailCheck" boolean NOT NULL,
    "eMailUnused" boolean NOT NULL,
    "nationalIdCheck" boolean NOT NULL,
    "mernisValidation" boolean NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE public."systemPersonnelValidator_employee"
(
    "systemPersonnelValidator_eMailCheck" boolean NOT NULL,
    "employee_eMail" "char" NOT NULL
);

CREATE TABLE public."systemPersonnelValidator_employer"
(
    "systemPersonnelValidator_eMailCheck" boolean NOT NULL,
    "employer_corporateMail" "char" NOT NULL
);

CREATE TABLE public."systemPersonnelValidator_employee"
(
    "systemPersonnelValidator_mernisValidation" boolean NOT NULL,
    "employee_birthYear" bit varying(4) NOT NULL
);

CREATE TABLE public."systemPersonnelValidator_employee"
(
    "systemPersonnelValidator_mernisValidation" boolean NOT NULL,
    "employee_nationalId" character varying(11) NOT NULL
);

ALTER TABLE public."systemPersonnelValidator_employee"
    ADD FOREIGN KEY ("systemPersonnelValidator_eMailCheck")
    REFERENCES public."systemPersonnelValidator" ("eMailCheck")
    NOT VALID;


ALTER TABLE public."systemPersonnelValidator_employee"
    ADD FOREIGN KEY ("employee_eMail")
    REFERENCES public.employee ("eMail")
    NOT VALID;


ALTER TABLE public."systemPersonnelValidator_employer"
    ADD FOREIGN KEY ("systemPersonnelValidator_eMailCheck")
    REFERENCES public."systemPersonnelValidator" ("eMailCheck")
    NOT VALID;


ALTER TABLE public."systemPersonnelValidator_employer"
    ADD FOREIGN KEY ("employer_corporateMail")
    REFERENCES public.employer ("corporateMail")
    NOT VALID;


ALTER TABLE public."systemPersonnelValidator"
    ADD FOREIGN KEY ("eMailUnused")
    REFERENCES public.employer ("corporateMail")
    NOT VALID;


ALTER TABLE public."systemPersonnelValidator"
    ADD FOREIGN KEY ("nationalIdCheck")
    REFERENCES public.employee ("nationalId")
    NOT VALID;


ALTER TABLE public."systemPersonnelValidator_employee"
    ADD FOREIGN KEY ("systemPersonnelValidator_mernisValidation")
    REFERENCES public."systemPersonnelValidator" ("mernisValidation")
    NOT VALID;


ALTER TABLE public."systemPersonnelValidator_employee"
    ADD FOREIGN KEY ("employee_birthYear")
    REFERENCES public.employee ("birthYear")
    NOT VALID;


ALTER TABLE public."systemPersonnelValidator_employee"
    ADD FOREIGN KEY ("systemPersonnelValidator_mernisValidation")
    REFERENCES public."systemPersonnelValidator" ("mernisValidation")
    NOT VALID;


ALTER TABLE public."systemPersonnelValidator_employee"
    ADD FOREIGN KEY ("employee_nationalId")
    REFERENCES public.employee ("nationalId")
    NOT VALID;

END;